[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
google-calendar3 = "5.0.2+20221229"
google-authenticator = "0.4.2"
